USE PIZZERIA;

DROP TABLE IF EXISTS dinein;
DROP TABLE IF EXISTS delivery;
DROP TABLE IF EXISTS pickup;
DROP TABLE IF EXISTS bridgetopping;
DROP TABLE IF EXISTS pizzadiscount;
DROP TABLE IF EXISTS orderdiscount;
DROP TABLE IF EXISTS topping;
DROP TABLE IF EXISTS pizza;
DROP TABLE IF EXISTS baseprice;
DROP TABLE IF EXISTS discount;
DROP TABLE IF EXISTS `order`;
DROP TABLE IF EXISTS customer;
